# Generated by Django 5.0.1 on 2024-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_product_date_product_image_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abouthead', models.CharField(max_length=100)),
                ('aboutdescription', models.TextField()),
                ('ourteam', models.CharField(max_length=100)),
            ],
        ),
    ]
