# Generated by Django 5.0.1 on 2024-02-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='abouthead',
            new_name='Title',
        ),
    ]
