# Generated by Django 5.0.1 on 2024-02-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_rename_aboutdescription_about_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Des',
            new_name='aboutdescription',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Title',
            new_name='abouthead',
        ),
    ]
