# Generated by Django 5.0.1 on 2024-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_rename_des_about_aboutdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=50)),
            ],
        ),
    ]
