# Generated by Django 5.0.1 on 2024-02-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='OurGoal',
            field=models.TextField(null=True),
        ),
    ]
