# Generated by Django 5.0.1 on 2024-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_about_ourgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Plan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
